# Generated by Django 3.2 on 2023-01-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'username')},
        ),
    ]
