# Generated by Django 3.2 on 2023-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_users_user_role_36d76d_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='role_idx'),
        ),
    ]
